### ISSUE TITLE
Cannot poll events due to `UndefVarError: info not defined`

### ISSUE THREAD

**Issue by nlw0** [jonathanBieler/SimpleDirectMediaLayer.jl#34]
Cannot use SDL2.event() right now because of this line. What is this function supposed to do?
https://github.com/jonathanBieler/SimpleDirectMediaLayer.jl/blob/8ba2c8595c09e73f7d33f23ee6d4ec7285f59a06/src/SimpleDirectMediaLayer.jl#L60

**Comment by jonathanBieler** [comment]
Hum, I think that was some debugging info, it should probably be removed.

**Comment by nlw0** [comment]
#35
