### ISSUE TITLE
Would be great to update to PackageProvider for the binary deps

### ISSUE THREAD

**Issue by NHDaly** [jonathanBieler/SimpleDirectMediaLayer.jl#38]
Wish list: If we switch to PackageProvider/PackageBuilder, it would make installing this easier, and would allow us to drop the Homebrew dependency. :)

**Comment by NHDaly** [comment]
And i thought of this because i was trying to `Pkg.add("SimpleDirectMediaLayer")` on my chromebook (I know, right?) and the current installation with BinDeps asked for `sudo`, but i don't know the sudo password for `chroot` (I need to look that up). But then i thought about how it's silly that we need to `sudo apt-get install sdl` in the first place, and it'd be better to just ship with pre-built libs.

**Comment by jonathanBieler** [comment]
I actually test this last week:

https://github.com/jonathanBieler/SDL2Builder

**Comment by NHDaly** [comment]
!! I love that! :) Haha what a happy coincidence! :D

Cool! So how'd it go? It looks like it worked to me. I downloaded a couple of the release archives and they seem reasonable!
Did you test the `BinaryProvider` part on this end?

**Comment by NHDaly** [comment]
Oh, actually, it looks like it worked really well!

I just downloaded the `build_SDL2.v0.1.0.jl` from your releases page (https://github.com/jonathanBieler/SDL2Builder/releases) and moved it to `deps/build.jl`, rebuilt, and everything seems to have worked! :) That's really awesome! I'll send that up as a PR here, and we/you can finish there work there? :)

**Comment by aviks** [comment]
Fixed by #41
